- content/FAQ/can-i-have.md
- content/FAQ/can-i.md
- content/FAQ/who-to-talk-to-for.md
- content/guides/local-development-environment-configuration.md
@stefanomainardi, @marcogiacomassi, @alessiopiazza and @paolomainardi: I'd like to have a feedback on the meat (and form of course) of those sections.
When we are OK with the statements we can begin publishing this work; addenda can be made at a later time, just put your ideas in the backlog here: https://trello.com/b/uJMBxjZZ/sparkfabrik-playbook-and-documentation
I know we didn't speak about this stuff, so take it as a stub and propose any modifications you see fit. If they are too much we can have a meeting in which to discuss our general rules.
> FAQ section

- content/guides/contributing-to-tech-blog.md
- content/recipes/tech-blog-checklist.md
I'm going to automerge this after thorogh reading and double check.
Feel free to fix things.
> Added "Contributing to tech blog" to guides section

- content/guides/local-development-environment-configuration.md
Just some steps to enjoy docker with Arch Linux
> dnsmasq instruction for Arch Linux SO

- content/recipes/kickstart-a-new-project.md
This PR brings in the contribution by @marcogiacomassi given months ago on private SF GitLab (https://gitlab.sparkfabrik.com/sparkfabrik/company-playbook/merge_requests/14) and never merged since it introduced some formatting regressions.
I polished it out and I'm going to merge this stuff right away.
> Recipes - Add slack info to project kickstart recipe

- content/our-company/job-interviews.md
Please, take this as a sort of draft/demo of the format we can adopt.
Review this branch to get a grasp on the process and let's talk face to face to elaborate on this topic, thanks.
> WIP: Added a chapter on how we perform job interviews.

- content/our-company/company-manifesto.md
The URL for the company manifiesto was incomplete
> Fix for the manifiesto link

- content/recipes/employee-onboarding.md
@paolomainardi @aysemeric I'd ask some help to review this page and see how it can be improved.
I surely forgot something important.
There are things we are not currently doing, I plan to structure all the information to do them and try to make them more automatic possible!
> WIP: employee onboarding process

- README.md
- custom/themes/spark-playbook/templates/home.html
- custom/themes/spark-playbook/templates/page.html
- custom/themes/spark-playbook/templates/search.html
refs #54: changed icon's link to playbook, added link to corporate site in welcome text
> refs #54: changed icon's link to playbook, added link to corporate

- custom/config.js
- custom/themes/spark-playbook/package-lock.json
- custom/themes/spark-playbook/package.json
Ho aggiunto gli a capo e il carattere `\xa0` (che è un NO-BREAK SPACE) per dare una buona formattazione allo snippet nel DOM.
Se preferite invece avere le configurazioni pulite, fate un fischio che gli do una pulita dai caratteri speciali.
> 45 ga tracking

- Makefile
- custom/raneto/contents.js
- custom/raneto/home.route.js
- custom/raneto/wildcard.route.js
> #65: Update Raneto's core files to the latest version

- content/tools-and-policies/access-to-the-office-during-covid19-pandemic.md
- content/tools-and-policies/approved-hardware-and-software.md
- content/tools-and-policies/attending-conferences.md
- content/tools-and-policies/communication-channels-and-register.md
- content/tools-and-policies/frontend-guidelines-drupal8.md
- content/tools-and-policies/management.md
- content/tools-and-policies/online-meetings-policy.md
- content/tools-and-policies/production-and-development.md
- content/tools-and-policies/tasks-and-time-tracking.md
And reordered the section, so the COVID page is on top.
> refs #81: added a page stub for COVID guidelines

- content/guides/local-development-environment-configuration.md
Update Local development environment configuration guide with systemd resolve configuration in a custom configuration file
> systemd resolve configuration in a custom configuration file

- content/guides/local-development-environment-configuration.md
@paolomainardi don't know who to address this. I reviewed a bit the grammar and general flow of the new paragraphs.
This was not asked for and it has been a personal initiative, feel free to reject this if you consider it unvaluable.
Also, check a couple comments I left since I'm not sure of a couple parts.
> Some rephrasing for smoother english.

- LICENSE.md
Using this one: https://creativecommons.org/licenses/by-nc/4.0/ - https://creativecommons.org/choose/results-one?license_code=by-nc&amp;jurisdiction=&amp;version=4.0&amp;lang=en
> Add a LICENSE - https://creativecommons.org/licenses/by-nc/4.0/

- content/guides/local-development-environment-configuration.md
> refs #000: Add documentation on how to upgrade the GCloud Auth plugin on Debian/Ubuntu users

- content/working-at-sparkfabrik/smart-working-contribution.md
This is a quick explanation of our Smart Working Contribute benefit (the same we named Tech Welfare or Smark Working Perks during development of the idea).
It has to be reviewed but not published until the policy has been released on our knowledge base.
> refs #145: Added the page alongside the referral bounty (same section).

- custom/themes/spark-playbook/public/js/app.js
This fixes the left menu open/all button.
TBH I have no idea why it wasn't working before, but I got the chance to refactor/modernize the code and logic.
> #189 Fix open/close all menu toggle

- content/guides/an-effective-onboarding-structure.md
- content/procedures/employee-onboarding.md
- content/tools-and-policies/management.md
- content/tools-and-policies/tasks-and-time-tracking.md
There are some additional issues to address.
> refs #187: bulk changed toggl to float.

- custom/patches/raneto+0.17.5.patch
- custom/themes/spark-playbook/public/js/app.js
- custom/themes/spark-playbook/scss/_components.code-highlight.scss
- custom/themes/spark-playbook/templates/layout.html
- docker-compose.yml
Added basic Mermaid graph rendering functionality.
- Mermaid code blocks are now rendered with a specific class
- Mermaid JS is now included in the pages via CSN
- node_modules folders is now mounted inside the container to allow the developer to modify Raneto's code and create a new patch for it
- former code highlight JS functions and CSS classes were slightly renamed to be more readable
> refs #199: Mermaid support

- content/resources/seniority-acc-cne-architect.md
- content/resources/seniority-acc-cne-professional.md
- content/resources/seniority-acc-dev-mid.md
- content/resources/seniority-acc-dev-senior.md
Pretty self-contained. Already reviewed internally, will merge it by myself.
> refs #214: introduced ownership attitude in approriate IACs.

- content/procedures/employee-onboarding.md
- content/tools-and-policies/github-copilot.md
* added a point about github copilot in the onboarding list
* added information about GHCP in the CLI
> refs #000: GH Copilot in onboarding checklist

- content/guides/local-development-environment-configuration.md
Enhancement
___
- Added a new command to configure Docker for GCP Artifact Registry in the local development environment setup guide
- The new command `gcloud auth configure-docker europe-west1-docker.pkg.dev` enables authentication for the Europe West 1 Artifact Registry
- This change enhances the local development setup process to include GCP Artifact Registry access
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>local-development-environment-configuration.md</strong><dd><code>Add GCP Artifact Registry Docker configuration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
> feat: add configuration for GCP artifact registry

- content/guides/local-development-environment-configuration.md
- content/procedures/employee-onboarding.md
- content/tools-and-policies/github-copilot.md
Updated information on how to ask for GH Copilot membership, plus added important steps in the onboarding checklist.
___
Documentation, Enhancement
___
* Improved developer onboarding process by integrating GitHub Copilot access during initial setup
* Added comprehensive documentation for FireStarter builds configuration for Drupal projects
* Updated GitHub Copilot subscription process to be part of standard onboarding
* Enhanced employee onboarding checklist with specific requirements for Drupal developers
* Streamlined access management by including necessary group memberships and authentication steps
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
<td>
<details> …
> New gh copilot policy, and more info about the onboarding.

- README.md
- content/tools-and-policies/github-copilot.md
Enhancement, Documentation
___
- Added comprehensive contribution guidelines:
* Detailed PR and branch naming conventions with examples
* Clear process for issue referencing
* Structured sections for different types of contributions
- Enhanced GitHub Copilot subscription process:
* Step-by-step instructions for requesting access
* Specific UI actions and communication channels
- Documentation improvements:
* Better organized README structure
* Removed outdated Trello reference
* Fixed typos and improved text clarity
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>README.md</strong><dd><code>Comprehensive update to contribution guidelines and documentation …
> refs #232 copilot procedure and readme improvements

- content/guides/transition-from-linux-to-macos-a-sparkfabrik-guide.md
Documentation
___
- Added a comprehensive guide to help Linux users transition to macOS environment
- Detailed explanation of macOS Unix-based system and its similarities to Linux
- Covered essential development tools including shell environment, cloud tools, and GUI applications
- Included detailed keyboard configuration and custom key bindings for Linux users
- Added package management guide with Homebrew commands and best practices
- Provided window management solutions and system optimization tips
- Documented future plans for container development migration from Docker to Lima in 2025
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
<td>
<details> …
> feat: add a transition guide from linux

- content/organization/governance.md
- content/resources/mgmtrole-acc-delivery-manager.md
- content/resources/mgmtrole-acc-staff-engineer.md
WIP
Added reviewers to keep an eye on those if they want to provide feeback on the go.
> refs #235: Ownerships for new roles added.
